Feat/all project page
esc-chula/esc-project-tracker pull request #16
Opened 2024-06-19 12:25 UTC by maxkubz

will implement more responsive for phone + clean code later

2024-06-21 09:57 UTC, ReawEiEi commented
- Checked About Docs ✔️

2024-06-26 12:54 UTC, LittleNa1000 requested changes
ส่วนใหญ่คอมเม้นแค่เปลี่ยนชื่อ Function อะๆ

2024-06-26 12:54 UTC, LittleNa1000 commented on apps/api/src/document_/document.service.ts
> +  async findDocumentByFilingId(filingId: string): Promise<Document[]> {
findDocumentsByFilingId น่าจะเหมาะกว่านะ

2024-06-26 12:54 UTC, LittleNa1000 commented on apps/api/src/trpc/routers/document.router.ts
> +        return this.documentService.findDocumentByFilingId(input.filingId);
findDocumentsByFilingId น่าจะเหมาะกว่านะ

2024-06-26 12:54 UTC, LittleNa1000 commented on apps/api/src/filing/filing.service.ts
> +  async findFilingWithFilter(filter: {
findFilingsWithFilter น่าจะเหมาะกว่านะ

2024-06-26 12:54 UTC, LittleNa1000 commented on apps/api/src/project_/project_.service.ts
> +  async findProjectWithFilter(filter: {
findProjectsWithFilter น่าจะเหมาะกว่านะ

2024-06-26 12:54 UTC, LittleNa1000 commented on apps/api/src/trpc/routers/filing.router.ts
> +    findFilingWithFilter: this.trpcService.trpc.procedure
findFilingsWithFilter

2024-06-26 12:54 UTC, LittleNa1000 commented on apps/api/src/trpc/routers/project.router.ts
> +    findProjectWithFilter: this.trpcService.trpc.procedure
findProjectsWithFilter

2024-06-26 12:54 UTC, LittleNa1000 commented on apps/api/src/user-proj/user-proj.service.ts
> +  async checkByUserIDAndProjectID({
checkUserProj หรือ hasUserProj น่าจะเหมาะกว่านะ ไม่ก็ชื่ออื่นที่สั้นกว่านี้

2024-06-26 12:54 UTC, LittleNa1000 commented on apps/api/src/trpc/routers/user-proj.router.ts
> +    checkByUserIDAndProjectID: this.trpcService.trpc.procedure
checkUserProj หรือ hasUserProj น่าจะเหมาะกว่านะ ไม่ก็ชื่ออื่นที่สั้นกว่านี้

2024-06-26 12:54 UTC, LittleNa1000 commented on apps/web/src/app/(authenticated)/projects/page.tsx
> +"use client";
คิดว่าไม่ต้องมี use client ก้ได้นะ

2024-06-26 12:54 UTC, LittleNa1000 commented on apps/web/src/components/all-projects/searchPanel.tsx
> +  projectFunc?: (project: ProjectType | FilingType) => any;
ไม่ใช่ props ตัวนี้หรอ

2024-06-26 12:54 UTC, LittleNa1000 commented on apps/web/src/components/project/filingMenuItem.tsx
> +    window.open(documents[0].pdfLink, "_blank");
documents[index].pdfLink

2024-06-26 12:54 UTC, LittleNa1000 commented on apps/web/src/interface/document.ts
> +export interface documentType {
DocumentType or Document

2024-06-26 12:54 UTC, LittleNa1000 commented on apps/web/src/service/findFilingWithFilter.ts
> +export default async function findFilingWithFilter(
findFilingsWithFilter

2024-06-26 12:54 UTC, LittleNa1000 commented on apps/web/src/service/findProjectWithFilter.ts
> +export default async function findProjectWithFilter(
findProjectsWithFilter

2024-06-29 04:04 UTC, maxkubz commented on apps/web/src/app/(authenticated)/projects/page.tsx
> +"use client";
@chickzilla

2024-06-29 04:04 UTC, maxkubz commented on apps/web/src/components/all-projects/searchPanel.tsx
> +  projectFunc?: (project: ProjectType | FilingType) => any;
@chickzilla

2024-06-29 04:22 UTC, maxkubz commented on apps/web/src/components/project/filingMenuItem.tsx
> +    window.open(documents[0].pdfLink, "_blank");
ต้องเป็น0ถูกละ ตัวindexไม่ได้ใช้ๆ ใส่มาละลืมเอาออก

2024-06-30 03:47 UTC, merged