Feat/my project
esc-chula/esc-project-tracker pull request #2
Opened 2024-05-24 20:45 UTC by chickzilla

2024-05-26 11:10 UTC, LittleNa1000 requested changes

2024-05-26 11:10 UTC, LittleNa1000 commented on apps/api/src/entities/document.entity.ts
is pdfLink: string missing?

2024-05-26 11:10 UTC, LittleNa1000 commented on apps/api/src/project_/project_.dto.ts
please change to reserveDate

2024-05-26 11:10 UTC, LittleNa1000 commented on apps/web/src/app/(authenticated)/my-projects/[projectId]/page.tsx
คิดว่า path นี้น่าจะเป็น /project/[projectId] มากกว่า เพราะหน้า Project เกี่ยวกับทั้ง /my-projects แล้วก็ /projects

2024-05-26 11:10 UTC, LittleNa1000 commented on apps/web/src/components/my-projects/allDocumentPanel.tsx
> +"use cliet";
typo

2024-05-26 11:10 UTC, LittleNa1000 commented on apps/web/src/interface/filling.ts
typo (filing)

2024-05-26 11:10 UTC, LittleNa1000 commented on apps/web/src/service/getFillingByProjectId.ts
typo (filing)

2024-05-26 11:10 UTC, LittleNa1000 commented on apps/web/src/service/getProjectByUserId.ts
คิดว่า getProjectsByUserId น่าจะเหมาะกว่านะ

2024-05-26 13:36 UTC, chickzilla commented on apps/api/src/project_/project_.dto.ts
done

2024-05-27 10:22 UTC, LittleNa1000 approved these changes

2024-05-27 11:49 UTC, merged