/home page and modified searchBar
esc-chula/esc-project-tracker pull request #20
Opened 2024-07-03 10:09 UTC by LittleNa1000

2024-07-30 16:28 UTC, chickzilla requested changes

2024-07-30 16:28 UTC, chickzilla commented on apps/web/src/components/project/latestItem.tsx
> +        router.push(`/projects/${projectId}`)
path มันเป็น /project/[projectId] รึป่าวคับ

2024-07-30 16:28 UTC, chickzilla commented on apps/web/src/app/(authenticated)/home/page.tsx
> +const mockData: FilingType[] = [
ไม่ใช่ก็เอาออกไหมคับ

2024-07-30 16:28 UTC, chickzilla commented on apps/web/src/components/project/myProjectData.tsx
> +    router.push(`/projects/${project.id}`)
path มันเป็น /project/[projectId] รึป่าวคับ

2024-07-31 11:23 UTC, LittleNa1000 commented on apps/web/src/components/project/latestItem.tsx
> +        router.push(`/projects/${projectId}`)
fixed

2024-07-31 11:23 UTC, LittleNa1000 commented on apps/web/src/app/(authenticated)/home/page.tsx
> +const mockData: FilingType[] = [
removed

2024-07-31 11:24 UTC, merged