Get notifications by user
esc-chula/esc-project-tracker pull request #24
Opened 2024-07-18 13:03 UTC by maxkubz

2024-07-18 16:37 UTC, LittleNa1000 requested changes
แก้นิดหน่อยนะคับ

2024-07-18 16:37 UTC, LittleNa1000 commented on apps/api/src/notification/notification.controller.ts
> +  findAllNotificationByUserId(@Body() obj: { userId: string }) {
ใช้คำว่า findNotificationsByUserId น่าจะเหมาะกว่านะ

2024-07-18 16:37 UTC, LittleNa1000 commented on apps/api/src/notification/notification.service.ts
> +      if (!user) throw new Error("user's not found");
แก้เป็น throw new Error("user not found");

2024-07-19 14:35 UTC, chickzilla approved these changes

2024-07-26 05:56 UTC, LittleNa1000 approved these changes
lgtm

2024-07-26 05:57 UTC, merged