Fix db schema
esc-chula/esc-project-tracker pull request #30
Opened 2024-07-27 17:35 UTC by maxkubz

- fix enum variable's name of filing status 
- add projectOwner to project entity
- add comment to document entity

2024-07-27 18:24 UTC, LittleNa1000 requested changes
แก้นิดหน่อยเรื่องการตั้งชื่อนะ

2024-07-27 18:24 UTC, LittleNa1000 commented on apps/api/src/entities/project.entity.ts
> +  projectOwner: User;
แค่คำว่า owner ก็พองับ

2024-07-27 18:24 UTC, LittleNa1000 commented on apps/api/src/constant/enum.ts
> +  FILING_CREATED = 'FILING_CREATED',
แก้เปน DOCUMENT_CREATED = 'DOCUMENT_CREATED'
เพราะ status นี้หมายถึง filing ที่มี document อย่างน้อย 1 อัน

2024-07-27 18:24 UTC, LittleNa1000 commented on apps/api/src/project_/project_.dto.ts
> +  projectOwner: string;
แค่คำว่า owner ก็พองับ

2024-07-27 18:24 UTC, LittleNa1000 commented on apps/api/src/project_/project_.service.ts
> +    if (!projectOwner)
อันนี้มันไม่ใช่ field ใน project จะแก้หรือไม่แก้ก็ได้นะ

2024-07-28 16:00 UTC, chickzilla approved these changes

2024-07-29 08:04 UTC, merged