Feat admin all project all filing
esc-chula/esc-project-tracker pull request #43
Opened 2024-08-16 15:32 UTC by chickzilla

เพิ่มหน้า projects/page.tsx เพิ่ม component ตาราง

ปรับ ui ตารางหน้า admin ให้ตรงตาม figma 

integrate service getLastestDocumentByFIlingId

-------------------------------------------------------------------
เพิ่มการ update filing โดยการสร้าง document ใหม่
https://jam.dev/c/795cc3b2-3082-4181-ad3d-b9f402e7fbaa

2024-08-16 15:35 UTC, chickzilla commented on apps/web/src/components/all-projects/searchPanel.tsx
ไม่ได้แก้ไร prettier ทำพิษ

2024-08-16 15:39 UTC, chickzilla commented on apps/web/src/components/project/filingMenuHeader.tsx
เพิ่มแค่ <thead>

2024-08-19 13:22 UTC, LittleNa1000 requested changes

2024-08-19 13:22 UTC, LittleNa1000 commented on apps/web/src/components/all-projects/selectTab.tsx
> +  const [isFilingUpdating, setIsFilingUpdating] =
isEditMode หรือ isUpdateMode น่าจะเหมาะกว่านะ

2024-08-19 13:22 UTC, LittleNa1000 commented on apps/web/src/components/all-projects/selectTab.tsx
> +          isUpdating={isFilingUpdating}
กุไม่ได้เข้าใจโค้ด 100% นะ แต่เดาว่า isUpdating กับ isFilingUpdating สื่อความหมายเดียวกัน เลยอยากให้ใช้ชื่อเดียวกันไปเลย (แต่ถ้าคนละค.หมายกันก็ใช้คนละชื่อนะ)

2024-08-19 13:22 UTC, LittleNa1000 commented on apps/web/src/components/project/filingMenu.tsx
> +            filingIdsNoUpdated.push(newDocument.filingId);
filingIdsNoUpdated.push(newDocument.name); เพราะ user ไม่รู้ว่า id นี้คือ filing ไหน

2024-08-19 13:22 UTC, LittleNa1000 commented on apps/web/src/components/project/projectMenu.tsx
> +            { value: 'notjoin', label: 'ไม่ได้เข้าร่วม' },
JOINED, NOT_JOINED

2024-08-19 13:22 UTC, LittleNa1000 commented on apps/web/src/components/project/projectMenu.tsx
>              return isJoined ? null : project;
`return (typeProject === 'join') === isJoined ? project : null;`

2024-08-19 17:26 UTC, LittleNa1000 requested changes

2024-08-19 17:26 UTC, LittleNa1000 commented on apps/web/src/components/project/projectMenuItem.tsx
> +            {isJoined ? null : <LogIn size={16} className="mr-2 inline" />}
`{!isJoined && <LogIn />}`

2024-08-19 17:26 UTC, LittleNa1000 commented on apps/web/src/components/project/projectMenuItem.tsx
> +      {isAdmin ? null : (
`{!isAdmin && <td />}`

2024-08-19 17:28 UTC, LittleNa1000 approved these changes
แก้คอมเม้นล่าสุดแล้ว merge ได้เลย

2024-08-19 18:59 UTC, merged