implement logic
esc-chula/esc-project-tracker pull request #45
Opened 2024-08-23 09:28 UTC by maxkubz

2024-08-23 20:21 UTC, LittleNa1000 requested changes
change เล็กน้อยครับ

2024-08-23 20:21 UTC, LittleNa1000 commented on apps/web/src/service/uploadFileToS3.ts
> +    console.log(res);
ลืม return res;

2024-08-24 03:54 UTC, maxkubz commented on apps/web/src/service/uploadFileToS3.ts
> +    console.log(res);
done

2024-08-27 15:06 UTC, LittleNa1000 approved these changes

2024-08-27 15:06 UTC, merged