Feat/admin homepage
esc-chula/esc-project-tracker pull request #49
Opened 2024-09-01 10:56 UTC by ReawEiEi

- Modify Admin Home Page
1.  Add filings filter bar (ดำเนินการ, ตีกลับ, อนุมัติ)
2. Change fetching data by default to fetch ALL filings and projects
3. Filter "FilingData" when clicked filter bar
4. Change "โครงการของฉัน" to "ตรวจสอบล่าสุด" (Not change any logic)

- Split User Display Card
1. Split card 
2. Have only 1 param that is UserName

2024-09-02 18:22 UTC, LittleNa1000 requested changes

2024-09-02 18:22 UTC, LittleNa1000 commented on apps/web/src/app/admin/home/page.tsx
> +const mockData: FilingType[] = [
ถ้าไม่ใช้ ลบได้เลยนะๆ

2024-09-02 18:22 UTC, LittleNa1000 commented on apps/web/src/app/admin/home/page.tsx
> +  const [isApprove, setIsApprove] = useState(false);
isContinued, isReturned, isApproved

2024-09-02 18:22 UTC, LittleNa1000 commented on apps/web/src/components/header/usercard.tsx
> +      const user = await getUser();
คิดว่าไม่ควรตั้งชื่อว่า getUser เพราะมัน return แค่ username อะ
getUsername น่าจะเหมาะกว่านะ ไม่ก็ทำให้มัน return มาทั้ง User เลย

2024-09-02 18:22 UTC, LittleNa1000 commented on apps/web/src/service/auth.ts
> +  return { userName: user.username };
ถ้าจะ return แค่ username สต.คิดว่า return username ที่เปน string ตรงๆ เลยก็ได้คับ

2024-09-02 18:22 UTC, LittleNa1000 commented on apps/web/src/interface/auth.ts
> +}
ถ้าจะ return แค่ username สต.คิดว่าใช้ username: string ไปเลยก็ได้ ไม่ต้องมี interface ครอบ

2024-09-03 14:31 UTC, ReawEiEi commented on apps/web/src/app/admin/home/page.tsx
> +    (project: { project: any }) => project.project,
done

2024-09-03 14:31 UTC, ReawEiEi commented on apps/web/src/app/admin/home/page.tsx
>            <Link href="/projects">
done

2024-09-03 14:32 UTC, ReawEiEi commented on apps/web/src/app/admin/home/page.tsx
done

2024-09-03 15:19 UTC, LittleNa1000 approved these changes

2024-09-03 15:26 UTC, merged