Dockerfile
esc-chula/esc-project-tracker pull request #62
Opened 2024-10-13 06:40 UTC by chickzilla

2024-10-14 04:04 UTC, maxkubz approved these changes

2024-10-14 09:18 UTC, LittleNa1000 requested changes

2024-10-14 09:18 UTC, LittleNa1000 commented on apps/web/Dockerfile
> +    INTANIA_AUTH_REDIRECT_URL=$INTANIA_AUTH_REDIRECT_URL
ต้องมี JWT_SECRET ด้วยนะ

2024-10-14 09:18 UTC, LittleNa1000 commented on docker-compose.yml
> +        INTANIA_AUTH_REDIRECT_URL: ${INTANIA_AUTH_REDIRECT_URL}
JWT_SECRET

2024-10-14 09:18 UTC, LittleNa1000 commented on apps/web/package.json
> +    "sharp": "^0.33.5",
ในโค้ดไม่มีต้องใช้ lib นี้นะ

2024-10-14 09:18 UTC, LittleNa1000 commented on apps/web/src/app/admin/status/page.tsx
> +'use client';
เป็น server component แทนได้มั้ย

2024-10-15 05:11 UTC, LittleNa1000 approved these changes

2024-10-15 05:11 UTC, merged